version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: python manage.py rqworker default
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - web

  db:
    image: postgres:latest
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest

volumes:
  pgdata: